apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-gateway-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "payment-gateway-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "payment-gateway-svc.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: grpc-otlp
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      protocol: TCP
